apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-website
  namespace: relay
  labels:
    app: relay-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-website
  template:
    metadata:
      labels:
        app: relay-website
    spec:
      containers:
        - image: austonst/mev-boost-relay@sha256:5ba9b6ea700926613eab33c4467c3cc132bdb89aff80d7a3224a5e894548d2e5
          name: relay-website
          args:
            - website
            - --network=hoodi
            - --listen-addr=:9060
            - --db=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URI):$(POSTGRES_PORT)/relay-db
            - --redis-uri=redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)
            - --redis-readonly-uri=redis://:$(REDIS_PASSWORD)@$(REDIS_HOST_RO):$(REDIS_PORT)
            - --relay-url=https://0x98f0ef62f00780cf8eb06701a7d22725b9437d4768bb19b363e882ae87129945ec206ec2dc16933f31d983f8225772b6@hoodi.aestus.live
            - --link-beaconchain=https://hoodi.beaconcha.in
            - --link-etherscan=https://hoodi.etherscan.io
          ports:
            - containerPort: 9060
              protocol: TCP
              name: web
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: password
          - name: POSTGRES_URI
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: password
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: redis
                key: host
          - name: REDIS_HOST_RO
            valueFrom:
              secretKeyRef:
                name: redis
                key: host_ro
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: redis
                key: port
          resources:
            #requests:
            #  memory: "1Gi"
            #  cpu: "500m"
            limits:
              memory: "1Gi"
      restartPolicy: Always