apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geth-teku
  namespace: mainnet
spec:
  selector:
    matchLabels:
      app: geth-teku
      lbtype: external
  serviceName: geth-teku
  podManagementPolicy: "Parallel"
  replicas: 1
  template:
    metadata:
      labels:
        app: geth-teku
        eth: mainnet
        lbtype: external
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - image: austonst/block-validation-geth@sha256:cf92a6454e50176597a90413c169d9493345ee97585cc4f08b9d25c0ee2e6665
          name: geth
          args:
            - --mainnet
            - --datadir=/data/geth
            - --http
            - --port=30305
            - --discovery.port=30306
            - --http.api=eth,net,personal,web3,flashbots
            - --http.addr=0.0.0.0
            - --http.port=8545
            - --http.vhosts=*
            - --metrics
            - --metrics.expensive
            - --metrics.port=6060
            - --metrics.addr=0.0.0.0
            - --authrpc.jwtsecret=/secrets/jwt
            - --authrpc.addr=0.0.0.0
            - --authrpc.vhosts=*
            - --maxpeers=50
            - --nat=extip:$(PUBLIC_IP)
          env:
          - name: PUBLIC_IP
            valueFrom:
              secretKeyRef:
                name: eth-lb-ip
                key: ip
          ports:
            - containerPort: 30305
              protocol: TCP
              name: geth-tcp
            - containerPort: 30306
              protocol: UDP
              name: geth-udp
            - containerPort: 8545
              protocol: TCP
              name: geth-rpc
          volumeMounts:
            - mountPath: /data
              name: eth-pvc
            - mountPath: /secrets
              name: jwt
          resources:
            requests:
              memory: "7Gi"
              cpu: "2000m"
            limits:
              memory: "10Gi"
              cpu: "3000m"
        - image: consensys/teku@sha256:3943a8c7aecb5e2f5379d67d26ebe2d37728b4a159f85f3b6b428f8676fc482d
          name: teku
          args:
            - --network=mainnet
            - --data-path=/data/teku
            - --p2p-enabled=true
            - --p2p-interface=0.0.0.0
            - --p2p-peer-lower-bound=100
            - --p2p-peer-upper-bound=75
            - --rest-api-enabled=true
            - --rest-api-port=5051
            - --rest-api-docs-enabled=true
            - --rest-api-interface=0.0.0.0
            - --rest-api-host-allowlist=*
            - --metrics-enabled=true
            - --metrics-host-allowlist=*
            - --metrics-port=8080
            - --ee-endpoint=http://localhost:8551
            - --ee-jwt-secret-file=/secrets/jwt
            - --p2p-port=9000
            - --p2p-udp-port=9001
            - --logging=INFO
            - --initial-state=https://beaconstate.ethstaker.cc/eth/v2/debug/beacon/states/finalized
            - --p2p-advertised-ip=$(PUBLIC_IP)
          env:
          - name: PUBLIC_IP
            valueFrom:
              secretKeyRef:
                name: eth-lb-ip
                key: ip
          ports:
            - containerPort: 9000
              protocol: TCP
              name: teku-tcp
            - containerPort: 9001
              protocol: UDP
              name: teku-udp
            - containerPort: 5051
              protocol: TCP
              name: teku-api
          volumeMounts:
            - mountPath: /data
              name: eth-pvc
            - mountPath: /secrets
              name: jwt
          resources:
            requests:
              memory: "7Gi"
              cpu: "2000m"
            limits:
              memory: "10Gi"
              cpu: "3000m"
      initContainers:
      - name: init-datadir
        image: busybox
        command: ['sh', '-c', "mkdir -p /data/geth /data/teku"]
        volumeMounts:
        - mountPath: /data
          name: eth-pvc
      restartPolicy: Always
      terminationGracePeriodSeconds: 600
      volumes:
        - name: jwt
          secret:
            secretName: eth-jwt
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: eth
                  operator: In
                  values:
                  - mainnet
              topologyKey: topology.kubernetes.io/zone
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: eth
                  operator: In
                  values:
                  - goerli
              topologyKey: topology.kubernetes.io/zone
  volumeClaimTemplates:
  - metadata:
      name: eth-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 1200Gi
