apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-api-builder
  namespace: relay
  labels:
    app: relay-api-builder
spec:
  replicas: 3
  selector:
    matchLabels:
      app: relay-api-builder
  template:
    metadata:
      labels:
        app: relay-api-builder
    spec:
      containers:
        - image: austonst/mev-boost-relay@sha256:bf698c6f68d2e13ad2e2cb9f2bfe42dc0c52118c6fe74961ef0ff78acb083c40
          name: builder
          args:
            - api
            - --network=holesky
            - --listen-addr=:9062
            - --apis=builder
            - --beacon-uris=http://int.a.holesky.aestus.live:5052,http://int.b.holesky.aestus.live:5052
            - --blocksim=http://block-queue:8080
            - --db=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URI):$(POSTGRES_PORT)/relay-db
            - --redis-uri=redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)
            - --redis-readonly-uri=redis://:$(REDIS_PASSWORD)@$(REDIS_HOST_RO):$(REDIS_PORT)
            - --bidengine-uri=redis://:$(REDIS_PASSWORD)@$(BIDENGINE_HOST):$(REDIS_PORT)
            - --bidengine-ro-uri=redis://:$(REDIS_PASSWORD)@$(BIDENGINE_HOST_RO):$(REDIS_PORT)
            - --memcached-uris=memcached-0.memcached.mcd.svc.cluster.local:11211,memcached-1.memcached.mcd.svc.cluster.local:11211
            - --secret-key=$(SECRET_KEY)
          ports:
            - containerPort: 9062
              protocol: TCP
              name: api
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: password
          - name: POSTGRES_URI
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: password
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: redis
                key: host
          - name: REDIS_HOST_RO
            valueFrom:
              secretKeyRef:
                name: redis
                key: host_ro
          - name: BIDENGINE_HOST
            valueFrom:
              secretKeyRef:
                name: redis
                key: host_bidengine
          - name: BIDENGINE_HOST_RO
            valueFrom:
              secretKeyRef:
                name: redis
                key: host_bidengine_ro
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: redis
                key: port
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: relay-key
                key: private
          - name: BLOCKSIM_MAX_CONCURRENT
            value: "0"
          - name: DISABLE_PAYLOAD_DATABASE_STORAGE
            value: "1"
          - name: ENABLE_BUILDER_CANCELLATIONS
            value: "1"
          resources:
            requests:
              memory: "900Mi"
              cpu: "500m"
            limits:
              memory: "900Mi"
      restartPolicy: Always
