apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-api-proposer
  namespace: relay
  labels:
    app: relay-api-proposer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: relay-api-proposer
  template:
    metadata:
      labels:
        app: relay-api-proposer
    spec:
      containers:
        - image: austonst/mev-boost-relay@sha256:7bd5e01caecbf2fbc1e9e6ba179ada535404e368742024d7752b0ae4b6171b39
          name: proposer
          args:
            - api
            - --network=holesky
            - --listen-addr=:9062
            - --apis=proposer
            - --beacon-uris=http://int.a.holesky.aestus.live:5052,http://int.b.holesky.aestus.live:5052
            - --db=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URI):$(POSTGRES_PORT)/relay-db
            - --redis-uris=$(REDIS_URIS)
            - --redis-pw=$(REDIS_PASSWORD)
            - --memcached-uris=memcached-0.memcached.mcd.svc.cluster.local:11211,memcached-1.memcached.mcd.svc.cluster.local:11211
            - --secret-key=$(SECRET_KEY)
          ports:
            - containerPort: 9062
              protocol: TCP
              name: api
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: password
          - name: POSTGRES_URI
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: password
          - name: REDIS_URIS
            valueFrom:
              secretKeyRef:
                name: redis
                key: allnodes
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: redis
                key: port
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: relay-key
                key: private
          - name: BLOCKSIM_MAX_CONCURRENT
            value: "0"
          - name: GETPAYLOAD_REQUEST_CUTOFF_MS
            value: "4000"
          resources:
            requests:
              memory: "5000Mi"
              cpu: "1000m"
            limits:
              memory: "5000Mi"
      restartPolicy: Always
