apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-housekeeper
  namespace: relay
  labels:
    app: relay-housekeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-housekeeper
  template:
    metadata:
      labels:
        app: relay-housekeeper
    spec:
      containers:
        - image: austonst/mev-boost-relay@sha256:b9438ae1ac267f890141eeffdf45e54dbed91e85f8f688ff402493bf2928f41a
          name: relay-housekeeper
          args:
            - housekeeper
            - --network=holesky
            - --beacon-uris=http://int.a.holesky.aestus.live:5052,http://int.b.holesky.aestus.live:5052
            - --db=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URI):$(POSTGRES_PORT)/relay-db
            - --redis-uri=redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)
            - --mev-commit-rpc=wss://chainrpc-wss.testnet.mev-commit.xyz
            - --ethereum-l1-rpc=http://int.a.holesky.aestus.live:8545
            - --provider-registry-addr=0xf4F10e18244d836311508917A3B04694D88999Dd
            - --validator-optin-router-addr=0xCae46e1013D33587180Db5933Abd75D977c2d7ab
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: password
          - name: POSTGRES_URI
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: password
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: redis
                key: host
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: redis
                key: port
          resources:
            requests:
              memory: "1300Mi"
              cpu: "2000m"
            limits:
              memory: "1300Mi"
      restartPolicy: Always
      terminationGracePeriodSeconds: 600