apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-api-data
  namespace: goerli
  labels:
    app: relay-api-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-api-data
  template:
    metadata:
      labels:
        app: relay-api-data
    spec:
      containers:
        - image: austonst/mev-boost-relay@sha256:7409999e294c94429a724f694703e75fad897aa3f5feca5c8c37545f187f7085
          name: data
          args:
            - api
            - --network=goerli
            - --listen-addr=:9062
            - --apis=data
            - --beacon-uris=http://10.108.0.12:3500,http://geth-prysm-0.geth-prysm.goerli.svc.cluster.local:3500,http://geth-lighthouse-0.geth-lighthouse.goerli.svc.cluster.local:3500
            - --blocksim=http://geth-prysm-0.geth-prysm.goerli.svc.cluster.local:8545
            - --db=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URI):$(POSTGRES_PORT)/relay-db
            - --redis-uris=$(REDIS_URIS)
            - --redis-pw=$(REDIS_PASSWORD)
            - --secret-key=$(SECRET_KEY)
          ports:
            - containerPort: 9062
              protocol: TCP
              name: api
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: password
          - name: POSTGRES_URI
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: password
          - name: REDIS_URIS
            valueFrom:
              secretKeyRef:
                name: redis
                key: allnodes
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: redis
                key: port
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: relay-key
                key: private
          resources:
            requests:
              memory: "250Mi"
              cpu: "125m"
            limits:
              memory: "500Mi"
              cpu: "250m"
      restartPolicy: Always
