apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-api-builder
  namespace: goerli
  labels:
    app: relay-api-builder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-api-builder
  template:
    metadata:
      labels:
        app: relay-api-builder
    spec:
      containers:
        - image: austonst/mev-boost-relay@sha256:18d429f2706db376a1ccfc85ce886b8b795702e3228d651601fa7eeb88fb1f62
          name: builder
          args:
            - api
            - --network=goerli
            - --listen-addr=:9062
            - --apis=builder
            - --beacon-uris=http://geth-lighthouse-0.geth-lighthouse.goerli.svc.cluster.local:5052,http://geth-lighthouse-1.geth-lighthouse.goerli.svc.cluster.local:5052
            - --blocksim=http://block-queue:8080
            - --db=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URI):$(POSTGRES_PORT)/relay-db
            - --redis-uris=$(REDIS_URIS)
            - --redis-pw=$(REDIS_PASSWORD)
            - --memcached-uris=memcached-goerli-0.memcached-goerli.mcd-goerli.svc.cluster.local:11211,memcached-goerli-1.memcached-goerli.mcd-goerli.svc.cluster.local:11211
            - --secret-key=$(SECRET_KEY)
          ports:
            - containerPort: 9062
              protocol: TCP
              name: api
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: password
          - name: POSTGRES_URI
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: password
          - name: REDIS_URIS
            valueFrom:
              secretKeyRef:
                name: redis
                key: allnodes
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: redis
                key: port
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: relay-key
                key: private
          - name: BLOCKSIM_MAX_CONCURRENT
            value: "0"
          - name: DISABLE_PAYLOAD_DATABASE_STORAGE
            value: "1"
          - name: ENABLE_BUILDER_CANCELLATIONS
            value: "1"
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
      restartPolicy: Always
