apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-api-internal
  namespace: goerli
  labels:
    app: relay-api-internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-api-internal
  template:
    metadata:
      labels:
        app: relay-api-internal
    spec:
      containers:
        - image: austonst/mev-boost-relay@sha256:6b2e206a5985c19a74a59414cba76e2722356ee24f7d2c605daa8994d76c65af
          name: internal
          args:
            - api
            - --network=goerli
            - --listen-addr=:9062
            - --apis=internal
            - --beacon-uris=http://geth-lighthouse-0.geth-lighthouse.goerli.svc.cluster.local:5052,http://geth-lighthouse-1.geth-lighthouse.goerli.svc.cluster.local:5052
            - --db=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URI):$(POSTGRES_PORT)/relay-db
            - --redis-uris=$(REDIS_URIS)
            - --redis-pw=$(REDIS_PASSWORD)
            - --memcached-uris=memcached-goerli-0.memcached-goerli.mcd-goerli.svc.cluster.local:11211,memcached-goerli-1.memcached-goerli.mcd-goerli.svc.cluster.local:11211
            - --secret-key=$(SECRET_KEY)
          ports:
            - containerPort: 9062
              protocol: TCP
              name: api
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: password
          - name: POSTGRES_URI
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: password
          - name: REDIS_URIS
            valueFrom:
              secretKeyRef:
                name: redis
                key: allnodes
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: redis
                key: port
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: relay-key
                key: private
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "250Mi"
              cpu: "250m"
      restartPolicy: Always
