apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-housekeeper
  namespace: goerli
  labels:
    app: relay-housekeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-housekeeper
  template:
    metadata:
      labels:
        app: relay-housekeeper
    spec:
      containers:
        - image: austonst/mev-boost-relay@sha256:f3a8399be75f0ecab54b1d51e3c5e9118b2876303f9fb6181379b0e6f534163e
          name: relay-housekeeper
          args:
            - housekeeper
            - --network=goerli
            - --beacon-uris=http://geth-prysm-0.geth-prysm.goerli.svc.cluster.local:3500,http://10.108.0.12:3500
            - --db=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URI):$(POSTGRES_PORT)/relay-db
            - --redis-uris=$(REDIS_URIS)
            - --redis-pw=$(REDIS_PASSWORD)
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: password
          - name: POSTGRES_URI
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: password
          - name: REDIS_URIS
            valueFrom:
              secretKeyRef:
                name: redis
                key: allnodes
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: redis
                key: port
          resources:
            requests:
              memory: "500Mi"
              cpu: "1000m"
            limits:
              memory: "1300Mi"
              cpu: "2000m"
      restartPolicy: Always
      terminationGracePeriodSeconds: 600