apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-housekeeper
  namespace: goerli
  labels:
    app: relay-housekeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-housekeeper
  template:
    metadata:
      labels:
        app: relay-housekeeper
    spec:
      containers:
        - image: austonst/mev-boost-relay@sha256:c4d0c661e549b86f0bba4a6004f196adf161f2b8400799082a362583a18cf406
          name: relay-housekeeper
          args:
            - housekeeper
            - --network=goerli
            - --beacon-uris=http://geth-prysm-0.geth-prysm.goerli.svc.cluster.local:3500,http://10.108.0.12:3500
            - --db=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URI):$(POSTGRES_PORT)/relay-db
            - --redis-uri=rediss://$(REDIS_USER):$(REDIS_PASSWORD)@$(REDIS_URI):$(REDIS_PORT)
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: password
          - name: POSTGRES_URI
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: port
          - name: REDIS_USER
            valueFrom:
              secretKeyRef:
                name: redis-default-credentials
                key: username
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-default-credentials
                key: password
          - name: REDIS_URI
            valueFrom:
              configMapKeyRef:
                name: redis-private-connection
                key: host
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: redis-private-connection
                key: port
          resources:
            requests:
              memory: "500Mi"
              cpu: "1000m"
            limits:
              memory: "1300Mi"
              cpu: "2000m"
      restartPolicy: Always
      terminationGracePeriodSeconds: 600