apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-website
  namespace: goerli
  labels:
    app: relay-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-website
  template:
    metadata:
      labels:
        app: relay-website
    spec:
      containers:
        - image: austonst/mev-boost-relay@sha256:b6ddee80d5e91fe5b36a5e6680e0b70d91a2e65a770c1c818250e2a4132366e2
          name: relay-website
          args:
            - website
            - --network=goerli
            - --listen-addr=:9060
            - --db=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URI):$(POSTGRES_PORT)/relay-db
            - --redis-uri=rediss://$(REDIS_USER):$(REDIS_PASSWORD)@$(REDIS_URI):$(REDIS_PORT)
            - --relay-url=https://0xab78bf8c781c58078c3beb5710c57940874dd96aef2835e7742c866b4c7c0406754376c2c8285a36c630346aa5c5f833@goerli.aestus.live
          ports:
            - containerPort: 9060
              protocol: TCP
              name: web
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: relay-user-credentials
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: relay-user-credentials
                key: password
          - name: POSTGRES_URI
            valueFrom:
              configMapKeyRef:
                name: relay-db-ref-private-connection
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                name: relay-db-ref-private-connection
                key: port
          - name: REDIS_USER
            valueFrom:
              secretKeyRef:
                name: redis-default-credentials
                key: username
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-default-credentials
                key: password
          - name: REDIS_URI
            valueFrom:
              configMapKeyRef:
                name: redis-private-connection
                key: host
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: redis-private-connection
                key: port
      restartPolicy: Always