apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-website
  namespace: goerli
  labels:
    app: relay-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-website
  template:
    metadata:
      labels:
        app: relay-website
    spec:
      containers:
        - image: austonst/mev-boost-relay@sha256:f3a8399be75f0ecab54b1d51e3c5e9118b2876303f9fb6181379b0e6f534163e
          name: relay-website
          args:
            - website
            - --network=goerli
            - --listen-addr=:9060
            - --db=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URI):$(POSTGRES_PORT)/relay-db
            - --redis-uris=$(REDIS_URIS)
            - --redis-pw=$(REDIS_PASSWORD)
            - --relay-url=https://0xab78bf8c781c58078c3beb5710c57940874dd96aef2835e7742c866b4c7c0406754376c2c8285a36c630346aa5c5f833@goerli.aestus.live
            - --link-beaconchain=https://goerli.beaconcha.in
            - --link-etherscan=https://goerli.etherscan.io
          ports:
            - containerPort: 9060
              protocol: TCP
              name: web
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: password
          - name: POSTGRES_URI
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: password
          - name: REDIS_URIS
            valueFrom:
              secretKeyRef:
                name: redis
                key: allnodes
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: redis
                key: port
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
      restartPolicy: Always