auth:
  enabled: true
  existingSecret: redis
  existingSecretPasswordKey: password

tls:
  enabled: false

master:
  persistence:
    enabled: true
    storageClass: csi-cinder-high-speed
    accessMode: ReadWriteOnce
    size: "1500Mi"
  resources:
    requests:
      memory: "1Gi"
      cpu: "100m"
    limits:
      memory: "1Gi"

replica:
  persistence:
    enabled: true
    storageClass: csi-cinder-high-speed
    accessMode: ReadWriteOnce
    size: "1500Mi"
  resources:
    requests:
      memory: "1Gi"
      cpu: "100m"
    limits:
      memory: "1Gi"

metrics:
  enabled: true
