apiVersion: v1
kind: Service
metadata:
  name: geth-prysm
  namespace: goerli
  labels:
    app: geth-prysm
spec:
  clusterIP: None
  selector:
    app: geth-prysm
  ports:
  - name: prysm-rpc
    port: 3500
    protocol: TCP
  - name: geth-rpc
    port: 8545
    protocol: TCP