apiVersion: v1
kind: Service
metadata:
  name: geth-teku-0
  namespace: goerli
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "geth-teku-0.goerli.aestus.live"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "30303"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "tcp"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "30"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "5"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold: "3"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-healthy-threshold: "5"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: geth-teku-0
  ports:
  - name: geth-tcp
    protocol: TCP
    port: 30303
    targetPort: 30303
  - name: geth-udp
    protocol: UDP
    port: 30304
    targetPort: 30304
  - name: teku-tcp
    protocol: TCP
    port: 9000
    targetPort: 9000
  - name: teku-udp
    protocol: UDP
    port: 9001
    targetPort: 9001
  - name: geth-rpc
    port: 8545
    protocol: TCP