#relay-api-mainnet
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-api-proposer
  namespace: mainnet
  labels:
    app: relay-api-proposer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: relay-api-proposer
  template:
    metadata:
      labels:
        app: relay-api-proposer
    spec:
      containers:
        - image: austonst/mev-boost-relay@sha256:776c4da287ab0d571deb77e07285bc9f78134596a89c6536a8a6bba39bbffc92
          name: api
          args:
            - api
            - --network=mainnet
            - --listen-addr=:9062
            - --apis=proposer
            - --beacon-uris=http://geth-prysm-0.geth-prysm.mainnet.svc.cluster.local:3500,http://geth-prysm-1.geth-prysm.mainnet.svc.cluster.local:3500,http://10.108.0.8:3500,http://geth-lighthouse-0.geth-lighthouse.mainnet.svc.cluster.local:5052,http://geth-lighthouse-1.geth-lighthouse.mainnet.svc.cluster.local:5052
            - --blocksim=http://block-queue:8080
            - --db=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URI):$(POSTGRES_PORT)/relay-db
            - --redis-uris=$(REDIS_URIS)
            - --redis-pw=$(REDIS_PASSWORD)
            - --memcached-uris=memcached-mainnet-0.memcached-mainnet.mcd-mainnet.svc.cluster.local:11211,memcached-mainnet-1.memcached-mainnet.mcd-mainnet.svc.cluster.local:11211
            - --secret-key=$(SECRET_KEY)
          ports:
            - containerPort: 9062
              protocol: TCP
              name: api
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: password
          - name: POSTGRES_URI
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: password
          - name: REDIS_URIS
            valueFrom:
              secretKeyRef:
                name: redis
                key: allnodes
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: redis
                key: port
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: relay-key
                key: private
          - name: BLOCKSIM_MAX_CONCURRENT
            value: "0"
          - name: GETPAYLOAD_REQUEST_CUTOFF_MS
            value: "4000"
          resources:
            requests:
              memory: "1000Mi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
      restartPolicy: Always
