#relay-api-mainnet
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-api-proposer
  namespace: mainnet
  labels:
    app: relay-api-proposer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: relay-api-proposer
  template:
    metadata:
      labels:
        app: relay-api-proposer
    spec:
      containers:
        - image: austonst/mev-boost-relay@sha256:905763031bfffd351c6d5779d3d7267887ebab0d3e7a309566f0144b06e349b2
          name: api
          args:
            - api
            - --network=mainnet
            - --listen-addr=:9062
            - --apis=proposer
            - --beacon-uris=http://geth-prysm-0.geth-prysm.mainnet.svc.cluster.local:3500,http://10.108.0.8:3500
            - --blocksim=http://block-queue:8080
            - --db=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URI):$(POSTGRES_PORT)/relay-db
            - --redis-uri=rediss://$(REDIS_USER):$(REDIS_PASSWORD)@$(REDIS_URI):$(REDIS_PORT)
            - --secret-key=$(SECRET_KEY)
          ports:
            - containerPort: 9062
              protocol: TCP
              name: api
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: password
          - name: POSTGRES_URI
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: port
          - name: REDIS_USER
            valueFrom:
              secretKeyRef:
                name: redis-default-credentials
                key: username
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-default-credentials
                key: password
          - name: REDIS_URI
            valueFrom:
              configMapKeyRef:
                name: redis-private-connection
                key: host
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: redis-private-connection
                key: port
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: relay-key
                key: private
          - name: BLOCKSIM_MAX_CONCURRENT
            value: "0"
          resources:
            requests:
              memory: "1000Mi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
      restartPolicy: Always
