#relay-api-mainnet
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-api-proposer
  namespace: relay
  labels:
    app: relay-api-proposer
spec:
  replicas: 4
  selector:
    matchLabels:
      app: relay-api-proposer
  template:
    metadata:
      labels:
        app: relay-api-proposer
    spec:
      containers:
        - image: austonst/mev-boost-relay@sha256:f88f6809c868b827c7035eae4ad99da7d0e0d05582fbd450003d0ef82c7e2b4c
          name: api
          args:
            - api
            - --network=mainnet
            - --listen-addr=:9062
            - --apis=proposer
            - --beacon-uris=http://int.a.mainnet.aestus.live:5052,http://int.b.mainnet.aestus.live:5052,http://int.c.mainnet.aestus.live:5052
            - --blocksim=http://block-queue:8080
            - --db=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URI):$(POSTGRES_PORT)/relay-db
            - --redis-uri=redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)
            - --redis-readonly-uri=redis://:$(REDIS_PASSWORD)@$(REDIS_HOST_RO):$(REDIS_PORT)
            - --bidengine-uri=redis://:$(REDIS_PASSWORD)@$(BIDENGINE_HOST):$(REDIS_PORT)
            - --bidengine-ro-uri=redis://:$(REDIS_PASSWORD)@$(BIDENGINE_HOST_RO):$(REDIS_PORT)
            - --memcached-uris=memcached-0.memcached.mcd.svc.cluster.local:11211,memcached-1.memcached.mcd.svc.cluster.local:11211
            - --latency-svc-uri=http://int.a.mainnet.aestus.live:3000/ip
            - --secret-key=$(SECRET_KEY)
          ports:
            - containerPort: 9062
              protocol: TCP
              name: api
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: password
          - name: POSTGRES_URI
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: password
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: redis
                key: host
          - name: REDIS_HOST_RO
            valueFrom:
              secretKeyRef:
                name: redis
                key: host_ro
          - name: BIDENGINE_HOST
            valueFrom:
              secretKeyRef:
                name: redis
                key: host_bidengine
          - name: BIDENGINE_HOST_RO
            valueFrom:
              secretKeyRef:
                name: redis
                key: host_bidengine_ro
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: redis
                key: port
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: relay-key
                key: private
          - name: BLOCKSIM_MAX_CONCURRENT
            value: "0"
          - name: GETPAYLOAD_REQUEST_CUTOFF_MS
            value: "4000"
          - name: GETHEADER_RESPONSE_RECEIVE_BY_MS
            value: "800"
          - name: LATENCY_TIMEOUT_MS
            value: "25"
          - name: USE_SSZ_ENCODING_PUBLISH_BLOCK
            value: "1"
          resources:
            requests:
              memory: "5Gi"
              cpu: "2000m"
            limits:
              memory: "5Gi"
      restartPolicy: Always
