#relay-api-mainnet
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-api-data
  namespace: relay
  labels:
    app: relay-api-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-api-data
  template:
    metadata:
      labels:
        app: relay-api-data
    spec:
      containers:
        - image: austonst/mev-boost-relay@sha256:96ddf01193d058495065cf21a463f11e76880c2ac6f2ef8a67ea7a8b9f2019c8
          name: api
          args:
            - api
            - --network=mainnet
            - --listen-addr=:9062
            - --apis=data
            - --beacon-uris=http://int.a.mainnet.aestus.live:5052,http://int.b.mainnet.aestus.live:5052,http://int.c.mainnet.aestus.live:5052
            - --db=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URI):$(POSTGRES_PORT)/relay-db
            - --redis-uri=redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)
            - --redis-readonly-uri=redis://:$(REDIS_PASSWORD)@$(REDIS_HOST_RO):$(REDIS_PORT)
            - --secret-key=$(SECRET_KEY)
          ports:
            - containerPort: 9062
              protocol: TCP
              name: api
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: password
          - name: POSTGRES_URI
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: password
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: redis
                key: host
          - name: REDIS_HOST_RO
            valueFrom:
              secretKeyRef:
                name: redis
                key: host_ro
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: redis
                key: port
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: relay-key
                key: private
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
      restartPolicy: Always
