#relay-api-mainnet
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-api
  namespace: mainnet
  labels:
    app: relay-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-api
  template:
    metadata:
      labels:
        app: relay-api
    spec:
      containers:
        - image: austonst/mev-boost-relay@sha256:3dc9cc1878460b8f6fd9bfc7675a42ab2614bdb8c60f6f6af962983fb58615f6
          name: relay-api
          args:
            - api
            - --network=mainnet
            - --listen-addr=:9062
            - --beacon-uris=http://geth-prysm-0.geth-prysm.mainnet.svc.cluster.local:3500
            - --blocksim=http://geth-prysm-0.geth-prysm.mainnet.svc.cluster.local:8545
            - --db=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URI):$(POSTGRES_PORT)/relay-db
            - --redis-uri=rediss://$(REDIS_USER):$(REDIS_PASSWORD)@$(REDIS_URI):$(REDIS_PORT)
            - --secret-key=$(SECRET_KEY)
          ports:
            - containerPort: 9062
              protocol: TCP
              name: api
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: relay-user-credentials
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: relay-user-credentials
                key: password
          - name: POSTGRES_URI
            valueFrom:
              configMapKeyRef:
                name: relay-db-ref-private-connection
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                name: relay-db-ref-private-connection
                key: port
          - name: REDIS_USER
            valueFrom:
              secretKeyRef:
                name: redis-default-credentials
                key: username
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-default-credentials
                key: password
          - name: REDIS_URI
            valueFrom:
              configMapKeyRef:
                name: redis-private-connection
                key: host
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: redis-private-connection
                key: port
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: relay-key
                key: private
      restartPolicy: Always
