#relay-housekeeper-mainnet
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-housekeeper
  namespace: mainnet
  labels:
    app: relay-housekeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-housekeeper
  template:
    metadata:
      labels:
        app: relay-housekeeper
    spec:
      containers:
        - image: austonst/mev-boost-relay@sha256:905763031bfffd351c6d5779d3d7267887ebab0d3e7a309566f0144b06e349b2
          name: relay-housekeeper
          args:
            - housekeeper
            - --network=mainnet
            - --beacon-uris=http://geth-prysm-0.geth-prysm.mainnet.svc.cluster.local:3500,http://10.108.0.8:3500
            - --db=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URI):$(POSTGRES_PORT)/relay-db
            - --redis-uri=rediss://$(REDIS_USER):$(REDIS_PASSWORD)@$(REDIS_URI):$(REDIS_PORT)
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: password
          - name: POSTGRES_URI
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: port
          - name: REDIS_USER
            valueFrom:
              secretKeyRef:
                name: redis-default-credentials
                key: username
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-default-credentials
                key: password
          - name: REDIS_URI
            valueFrom:
              configMapKeyRef:
                name: redis-private-connection
                key: host
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: redis-private-connection
                key: port
          - name: DISABLE_SSE_PAYLOAD_ATTRIBUTES
            value: "1"
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
      restartPolicy: Always
      terminationGracePeriodSeconds: 600