#relay-website-mainnet
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-website
  namespace: relay
  labels:
    app: relay-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-website
  template:
    metadata:
      labels:
        app: relay-website
    spec:
      containers:
        - image: austonst/mev-boost-relay@sha256:96ddf01193d058495065cf21a463f11e76880c2ac6f2ef8a67ea7a8b9f2019c8
          name: relay-website
          args:
            - website
            - --network=mainnet
            - --listen-addr=:9060
            - --db=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URI):$(POSTGRES_PORT)/relay-db
            - --redis-uri=redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)
            - --redis-readonly-uri=redis://:$(REDIS_PASSWORD)@$(REDIS_HOST_RO):$(REDIS_PORT)
            - --relay-url=https://0xa15b52576bcbf1072f4a011c0f99f9fb6c66f3e1ff321f11f461d15e31b1cb359caa092c71bbded0bae5b5ea401aab7e@aestus.live
          ports:
            - containerPort: 9060
              protocol: TCP
              name: web
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: password
          - name: POSTGRES_URI
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: password
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: redis
                key: host
          - name: REDIS_HOST_RO
            valueFrom:
              secretKeyRef:
                name: redis
                key: host_ro
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: redis
                key: port
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
      restartPolicy: Always