{
 "title": "Relay",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Namespace", "query": "mainnet, goerli" }
  ]
 },
 "panels": [
  {
   "title": "submitNewBlock Calls Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(msg) (count_over_time({namespace=\"$Namespace\", app=\"relay-api-builder\"} | logfmt | method = `submitNewBlock` | msg =~ `^block validation.*` [$__interval]))",
     "legendFormat": "{{msg}}"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$Namespace\", app=\"relay-api-builder\"} | logfmt | method = `submitNewBlock` | msg =~ `^incorrect prev_randao.*` [$__interval]))",
     "legendFormat": "incorrect prev_randao"
    },
    {
     "expr": "sum by(msg) (count_over_time({namespace=\"$Namespace\", app=\"relay-api-builder\"} | logfmt | method = `submitNewBlock` | msg = `prev_randao is not known yet` [$__interval]))",
     "legendFormat": "{{msg}}"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$Namespace\", app=\"relay-api-builder\"} | logfmt | method = `submitNewBlock` | msg =~ `^already have a newer payload.*` [$__interval]))",
     "legendFormat": "already have a newer payload"
    },
    {
     "expr": "sum by(msg) (count_over_time({namespace=\"$Namespace\", app=\"relay-api-builder\"} | logfmt | method = `submitNewBlock` | msg = `rejecting submission because payload for this slot was already delivered` [$__interval]))",
     "legendFormat": "{{msg}}"
    },
    {
     "expr": "sum by(msg) (count_over_time({namespace=\"$Namespace\", app=\"relay-api-builder\"} | logfmt | method = `submitNewBlock` | msg !~ `^block validation.*` | msg !~ `^incorrect prev_randao.*` | msg != `prev_randao is not known yet` | msg !~ `^already have a newer payload.*` | msg != `received block from builder` | msg != `rejecting submission because payload for this slot was already delivered` | msg != `could not find slot duty` [$__interval]))",
     "legendFormat": "UNTRACKED: {{msg}}"
    }
   ]
  },
  {
   "title": "submitNewBlock Calls Per Slot",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by(slot) (count_over_time({namespace=\"$Namespace\", app=\"relay-api-builder\"} | logfmt | method = `submitNewBlock` | msg =~ `^block validation successful.*` [$__range]))"
    },
    {
     "expr": "sum by(slot) (count_over_time({namespace=\"$Namespace\", app=\"relay-api-builder\"} | logfmt | method = `submitNewBlock` | msg =~ `^block validation failed.*` [$__range]))"
    },
    {
     "expr": "sum by(slot) (count_over_time({namespace=\"$Namespace\", app=\"relay-api-builder\"} | logfmt | method = `submitNewBlock` | msg =~ `^incorrect prev_randao.*` [$__range]))"
    },
    {
     "expr": "sum by(slot) (count_over_time({namespace=\"$Namespace\", app=\"relay-api-builder\"} | logfmt | method = `submitNewBlock` | msg = `prev_randao is not known yet` [$__range]))",
     "legendFormat": "{{msg}}"
    },
    {
     "expr": "sum by(slot) (count_over_time({namespace=\"$Namespace\", app=\"relay-api-builder\"} | logfmt | method = `submitNewBlock` | msg =~ `^already have a newer payload.*` [$__range]))",
     "legendFormat": "already have a newer payload"
    },
    {
     "expr": "sum by(slot) (count_over_time({namespace=\"$Namespace\", app=\"relay-api-builder\"} | logfmt | method = `submitNewBlock` | msg = `rejecting submission because payload for this slot was already delivered` [$__range]))",
     "legendFormat": "Already Delivered"
    },
    {
     "expr": "sum by(slot, namespace) (count_over_time({namespace=\"$Namespace\", app=\"relay-api-builder\"} | logfmt | method = `submitNewBlock` | msg !~ `^block validation.*` | msg !~ `^incorrect prev_randao.*` | msg != `prev_randao is not known yet` | msg !~ `^already have a newer payload.*` | msg != `received block from builder` | msg != `rejecting submission because payload for this slot was already delivered` [$__range]))",
     "legendFormat": "UNTRACKED: {{msg}}"
    }
   ]
  },
  {
   "title": "Blocks Submitted By Slot",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count by(slot) (count_over_time({namespace=\"$Namespace\", app=\"relay-api-builder\"} |= `` | logfmt | method = `submitNewBlock` | msg = `received block from builder` [$__range]))",
     "legendFormat": "{{slot}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Blocks Submitted In Time Range By Builder",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum by(builderPubkey) (count_over_time({namespace=\"$Namespace\", app=\"relay-api-builder\"} |= `` | logfmt | method = `submitNewBlock` | msg = `received block from builder` [$__range]))",
     "legendFormat": "{{builderPubkey}}"
    }
   ]
  },
  {
   "title": "Questionable Log Entries",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{namespace=\"$Namespace\", app=~\"relay-api-builder|relay-api-proposer|relay-api-data|relay-website|relay-housekeeper\"} | logfmt | level != `info` | error !~ `.*requested slot number is higher than head slot number` | msg !~ `^missed slot.*` | msg !~ `.*not a known validator.*` | msg != `could not find slot duty`",
     "maxLines": 200
    }
   ]
  },
  {
   "title": "Payloads Delivered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$Namespace\", app=\"relay-api-proposer\"} | logfmt | method = `getPayload` | msg = `execution payload delivered` [$__interval]))",
     "legendFormat": "Payloads"
    }
   ]
  },
  {
   "title": "Payloads Delivered in Time Range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$Namespace\", app=\"relay-api-proposer\"} | logfmt | method = `getPayload` | msg = `execution payload delivered` [$__range]))"
    }
   ]
  },
  {
   "title": "Current Slot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "{namespace=\"$Namespace\", app=\"relay-api-proposer\"} | logfmt | msg  =~ `updated headSlot.*`"
    }
   ]
  },
  {
   "title": "Last Proposed Value",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "{namespace=\"$Namespace\", app=\"relay-api-proposer\"} | logfmt | method = `getPayload` | msg = `execution payload delivered`"
    },
    {
     "expr": "{namespace=\"$Namespace\", app=\"relay-api-builder\"} | logfmt | line_format `eth={{ divf .value 1000000000000000000 | printf \"%3.6f\" }}` | logfmt | msg = `block validation successful`"
    }
   ]
  },
  {
   "title": "Last Proposed Slot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "{namespace=\"$Namespace\", app=\"relay-api-proposer\"} | logfmt | method = `getPayload` | msg = `execution payload delivered`"
    },
    {
     "expr": "{namespace=\"$Namespace\", app=\"relay-api-builder\"} | logfmt | line_format `eth={{ divf .value 1000000000000000000 | printf \"%3.6f\" }}` | logfmt | msg = `block validation successful`"
    }
   ]
  },
  {
   "title": "Block Validation Duration/TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{namespace=\"$Namespace\", app=\"relay-api-builder\"} |= `block validation successful` | logfmt"
    }
   ]
  },
  {
   "title": "Block Validation Duration by Builder",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "{namespace=\"$Namespace\", app=\"relay-api-builder\"} |= `block validation successful` | logfmt"
    }
   ]
  },
  {
   "title": "Validator Registration Timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{namespace=\"$Namespace\", app=\"relay-api-proposer\"} | logfmt | method = `registerValidator` | msg = `validator registrations call processed`",
     "legendFormat": "Payloads"
    }
   ]
  },
  {
   "title": "Validator Registration Time per Validator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "{namespace=\"$Namespace\", app=\"relay-api-proposer\"} | logfmt | method = `registerValidator` | msg = `validator registrations call processed`",
     "legendFormat": "Payloads"
    }
   ]
  },
  {
   "title": "Validation Prio Queue Length",
   "type": "timeseries",
   "description": "The validation queue length as reported by the priority queue. These are blocks that have been added to the queue but not picked up by a worker routine. Reported as soon as a block as added to the queue, so minimum is 1.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{namespace=\"$Namespace\", app=\"block-queue\"} |= `Request added to queue`"
    }
   ]
  },
  {
   "title": "Validation numWaiting",
   "type": "timeseries",
   "description": "The full number of blocks either undergoing or waiting for validation as reported by the builder API",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "{namespace=\"$Namespace\", app=\"relay-api-builder\"} | logfmt | msg = `block validation successful`"
    }
   ]
  },
  {
   "title": "Validator Registration Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{namespace=\"$Namespace\", app=\"relay-api-proposer\"} | logfmt | method = `registerValidator` | msg = `validator registrations call processed`",
     "legendFormat": "Payloads"
    }
   ]
  },
  {
   "title": "Validator Registration Time Quantiles (1 hr)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "quantile_over_time(0.5, {namespace=\"$Namespace\", app=\"relay-api-proposer\"} | logfmt | method = `registerValidator` | msg = `validator registrations call processed` | unwrap timeNeededSec [1h]) by (method)",
     "legendFormat": "50%",
     "maxLines": 5000
    },
    {
     "expr": "quantile_over_time(0.95, {namespace=\"$Namespace\", app=\"relay-api-proposer\"} | logfmt | method = `registerValidator` | msg = `validator registrations call processed` | unwrap timeNeededSec [1h]) by (method)",
     "legendFormat": "95%",
     "maxLines": 5000
    },
    {
     "expr": "quantile_over_time(0.99, {namespace=\"$Namespace\", app=\"relay-api-proposer\"} | logfmt | method = `registerValidator` | msg = `validator registrations call processed` | unwrap timeNeededSec [1h]) by (method)",
     "legendFormat": "99%",
     "maxLines": 5000
    },
    {
     "expr": "quantile_over_time(0.999, {namespace=\"$Namespace\", app=\"relay-api-proposer\"} | logfmt | method = `registerValidator` | msg = `validator registrations call processed` | unwrap timeNeededSec [1h]) by (method)",
     "legendFormat": "99.9%",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Block Validation Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{namespace=\"$Namespace\", app=\"block-queue\"} |= `duration`"
    }
   ]
  },
  {
   "title": "Max Validation Duration by Slot",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "{namespace=\"$Namespace\", app=\"relay-api-builder\"} |= `block validation successful` | logfmt"
    }
   ]
  },
  {
   "title": "Builders w/ Incorrect Fee Recipients",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "count by(builderPubkey) (count_over_time({namespace=\"$Namespace\", app=\"relay-api-builder\"} |= `fee recipient does not match` | logfmt [$__interval]))"
    }
   ]
  },
  {
   "title": "Block Validation Duration Quantiles (5 min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "quantile_over_time(0.5, {namespace=\"$Namespace\", app=\"relay-api-builder\"} |= `block validation successful` | logfmt | unwrap duration [5m]) by (builderIsHighPrio)",
     "legendFormat": "50%",
     "maxLines": 5000
    },
    {
     "expr": "quantile_over_time(0.95, {namespace=\"$Namespace\", app=\"relay-api-builder\"} |= `block validation successful` | logfmt | unwrap duration [5m]) by (builderIsHighPrio)",
     "legendFormat": "95%",
     "maxLines": 5000
    },
    {
     "expr": "quantile_over_time(0.99, {namespace=\"$Namespace\", app=\"relay-api-builder\"} |= `block validation successful` | logfmt | unwrap duration [5m]) by (builderIsHighPrio)",
     "legendFormat": "99%",
     "maxLines": 5000
    },
    {
     "expr": "quantile_over_time(0.999, {namespace=\"$Namespace\", app=\"relay-api-builder\"} |= `block validation successful` | logfmt | unwrap duration [5m]) by (builderIsHighPrio)",
     "legendFormat": "99.9%",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Block Validation Duration Quantiles (1 hr)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
   "targets": [
    {
     "expr": "quantile_over_time(0.5, {namespace=\"$Namespace\", app=\"relay-api-builder\"} |= `block validation successful` | logfmt | unwrap duration [1h]) by (builderIsHighPrio)",
     "legendFormat": "50%",
     "maxLines": 5000
    },
    {
     "expr": "quantile_over_time(0.95, {namespace=\"$Namespace\", app=\"relay-api-builder\"} |= `block validation successful` | logfmt | unwrap duration [1h]) by (builderIsHighPrio)",
     "legendFormat": "95%",
     "maxLines": 5000
    },
    {
     "expr": "quantile_over_time(0.99, {namespace=\"$Namespace\", app=\"relay-api-builder\"} |= `block validation successful` | logfmt | unwrap duration [1h]) by (builderIsHighPrio)",
     "legendFormat": "99%",
     "maxLines": 5000
    },
    {
     "expr": "quantile_over_time(0.999, {namespace=\"$Namespace\", app=\"relay-api-builder\"} |= `block validation successful` | logfmt | unwrap duration [1h]) by (builderIsHighPrio)",
     "legendFormat": "99.9%",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Builder Identification (Proposed Blocks)",
   "type": "table",
   "description": "Only meaningful if there was a proposal in the time range and the slot is displayed, otherwise these aren't limited to proposed blocks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "{namespace=\"$Namespace\", app=\"relay-api-proposer\"} | logfmt | method = `getPayload` | msg = `execution payload delivered`"
    },
    {
     "expr": "{namespace=\"$Namespace\", app=\"relay-api-builder\"} | logfmt | msg = `block validation successful`"
    }
   ]
  },
  {
   "title": "Full Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Proposer API",
     "type": "logs",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "{namespace=\"$Namespace\", app=\"relay-api-proposer\"} | logfmt",
       "maxLines": 200
      }
     ]
    },
    {
     "title": "Builder API",
     "type": "logs",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "{namespace=\"$Namespace\", app=\"relay-api-builder\"} | logfmt",
       "maxLines": 200
      }
     ]
    }
   ]
  }
 ]
}