apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: mainnet
spec:
  type: ClusterIP
  selector:
    app: homepage
  ports:
    - name: web
      port: 80
      protocol: TCP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: homepage
  namespace: mainnet
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: homepage
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
