apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: relay
  labels:
   app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - image: maxbirge/relay-homepage@sha256:cd30f40b959a858decd18786690c1f5c3562a140c8268d66e8760cd2a5212460
          name: homepage
          ports:
            - containerPort: 80
              protocol: TCP
              name: web
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
      restartPolicy: Always
