apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: mainnet
  labels:
   app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - image: austonst/aestus-homepage@sha256:ee58fd2071e9b49c4b483a9e611c99d65277f31827954fc23193a55dcae89aa0
          name: homepage
          ports:
            - containerPort: 80
              protocol: TCP
              name: web
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      restartPolicy: Always
