apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: relay
  labels:
   app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - image: austonst/aestus-homepage@sha256:94fb57d13e8f44000aa9e98296b8664c7877ccd435336a9f9021cd27fe4e7810
          name: homepage
          ports:
            - containerPort: 80
              protocol: TCP
              name: web
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
      restartPolicy: Always
