apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-el-geth-goerli
  labels:
    app: relay-el-geth-goerli
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: relay-el-geth-goerli
  template:
    metadata:
      labels:
        app: relay-el-geth-goerli
    spec:
      containers:
        - image: austonst/block-validation-geth@sha256:cf92a6454e50176597a90413c169d9493345ee97585cc4f08b9d25c0ee2e6665
          name: relay-el-geth-goerli
          args:
            - --goerli
            - --datadir=/el-geth
            - --http
            - --port=3001
            - --discovery.port=3002
            - --http.api=eth,net,personal,web3,flashbots
            - --http.addr=0.0.0.0
            - --http.port=8547
            - --http.vhosts=*
            - --metrics
            - --metrics.expensive
            - --metrics.port=6060
            - --metrics.addr=0.0.0.0
            - --authrpc.jwtsecret=/secrets/jwt
            - --authrpc.addr=0.0.0.0
            - --authrpc.vhosts=*
            - --maxpeers=50
#            - --nat=extip:136.243.4.36
          ports:
            - containerPort: 3001
              protocol: TCP
              name: el-geth-tcp
            - containerPort: 3002
              protocol: UDP
              name: el-geth-udp
            - containerPort: 8547
              protocol: TCP
              name: el-geth-rpc
            - containerPort: 8551
              protocol: TCP
              name: el-geth-engine
          volumeMounts:
            - mountPath: /el-geth
              name: eth-pvc
            - mountPath: /secrets
              name: jwt
      restartPolicy: Always
      terminationGracePeriodSeconds: 600
      volumes:
        - name: eth-pvc
          persistentVolumeClaim:
            claimName: ethereum-goerli-pvc
        - name: jwt
          secret:
            secretName: eth-goerli-jwt
