kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ethereum-goerli-pvc
spec:
  storageClassName: csi-cinder-high-speed
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 350Gi
