architecture: high-availability
replicaCount: 2

extraEnvVars:
  - name: MEMCACHED_CACHE_SIZE
    value: "128"
  - name: MEMCACHED_MAX_ITEM_SIZE
    value: "8388608"

resources:
  requests:
    memory: 256Mi
    cpu: "100m"

persistence:
  enabled: true
  storageClass: do-block-storage
  accessMode: ReadWriteOnce
  size: 8Gi
