usePassword: true
existingSecret: redis
existingSecretPasswordKey: password

tls:
  enabled: false

persistence:
  enabled: true
  storageClass: do-block-storage
  accessMode: ReadWriteOnce
  size: "1200Mi"

redis:
  resources:
    requests:
      memory: "1Gi"
      cpu: "100m"

metrics:
  enabled: true
