kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cl-goerli-pvc
spec:
  storageClassName: csi-cinder-high-speed
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
