#http://geth-prysm-0.geth-prysm.mainnet.svc.cluster.local:8545,http://geth-prysm-1.geth-prysm.mainnet.svc.cluster.local:8545,http://10.108.0.8:8545,http://geth-lighthouse-0.geth-lighthouse.mainnet.svc.cluster.local:8545,http://geth-lighthouse-1.geth-lighthouse.mainnet.svc.cluster.local:8545
apiVersion: apps/v1
kind: Deployment
metadata:
  name: block-queue
  namespace: mainnet
  labels:
    app: block-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: block-queue
  template:
    metadata:
      labels:
        app: block-queue
    spec:
      containers:
      - image: flashbots/prio-load-balancer@sha256:6ddd9f619451b5c47805673438b47d7522bb0188566b802f85dadd1daa45bb9f
        name: queue
        args:
          - /app/prio-load-balancer
          - --http=0.0.0.0:8080
          - --nodes=http://geth-lighthouse-0.geth-lighthouse.mainnet.svc.cluster.local:8545,http://geth-lighthouse-1.geth-lighthouse.mainnet.svc.cluster.local:8545
          - --redis=dev
        ports:
          - containerPort: 8080
            protocol: TCP
            name: api
        resources:
          requests:
            memory: "250Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
      restartPolicy: Always