#http://geth-lighthouse-0.geth-lighthouse.mainnet.svc.cluster.local:8545,http://geth-lighthouse-1.geth-lighthouse.mainnet.svc.cluster.local:8545,http://geth-lighthouse-2.geth-lighthouse.mainnet.svc.cluster.local:8545
apiVersion: apps/v1
kind: Deployment
metadata:
  name: block-queue
  namespace: relay
  labels:
    app: block-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: block-queue
  template:
    metadata:
      labels:
        app: block-queue
    spec:
      containers:
      - image: flashbots/prio-load-balancer@sha256:346b7e2050e9a0db9748e5baffe0b1137bf32ab9680c7b45d47204b5b5cbde04
        name: queue
        args:
          - /app/prio-load-balancer
          - --http=0.0.0.0:8080
          - --nodes=http://int.a.mainnet.aestus.live:8545?_workers=20,http://int.b.mainnet.aestus.live:8545?_workers=20,http://int.c.mainnet.aestus.live:8545?_workers=20
          - --redis=dev
        ports:
          - containerPort: 8080
            protocol: TCP
            name: api
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "1Gi"
      restartPolicy: Always