#service.yaml
apiVersion: v1
kind: Service
metadata:
  name: block-queue
  namespace: relay
spec:
  type: ClusterIP
  selector:
      app: block-queue
  ports:
  - name: api
    port: 8080
    targetPort: 8080
    protocol: TCP