#spec:
#  template:
#    metadata:
#      containers:
#      - args:
#        - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services #add tcp config-map
#        - --udp-services-configmap=$(POD_NAMESPACE)/udp-services #add udp config-map
[{ "op": "add", 
   "path": "/spec/template/spec/containers/0/args/-", 
   "value": "--tcp-services-configmap=$(POD_NAMESPACE)/tcp-services"},
{ "op": "add", 
   "path": "/spec/template/spec/containers/0/args/-", 
   "value": "--udp-services-configmap=$(POD_NAMESPACE)/udp-services"}]