spec:
  ports:
  - name: proxy-tcp-geth-a #custom tcp proxy for geth-A
    port: 30303
    protocol: TCP
    targetPort: 30303
  - name: proxy-udp-geth-a #custom udp proxy for geth-A
    port: 30303
    protocol: UDP
    targetPort: 30303
  - name: proxy-tcp-geth-b #custom tcp proxy for geth-B
    port: 30304
    protocol: TCP
    targetPort: 30304
  - name: proxy-udp-geth-b #custom udp proxy for geth-B
    port: 30304
    protocol: UDP
    targetPort: 30304
  - name: proxy-tcp-teku #custom tcp proxy for teku
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: proxy-udp-teku #custom udp proxy for teku
    port: 9000
    protocol: UDP
    targetPort: 9000
  - name: proxy-tcp-prysm #custom tcp proxy for prysm
    port: 13000
    protocol: TCP
    targetPort: 13000
  - name: proxy-udp-prysm #custom udp proxy for prysm
    port: 12000
    protocol: UDP
    targetPort: 12000