apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  30303: "geth-teku-0.geth-teku.mainnet.svc.cluster.local:30303"
  30304: "geth-prysm-0.geth-prysm.mainnet.svc.cluster.local:30304"
  9000: "geth-teku-0.geth-teku.mainnet.svc.cluster.local"
  12000: "geth-prysm-0.geth-prysm.mainnet.svc.cluster.local:12000"