apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  30303: "mainnet/geth-teku:30303"
  30304: "mainnet/geth-prysm:30304"
  9000: "mainnet/geth-teku:9000"
  12000: "mainnet/geth-prysm:12000"