apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  namespace: goerli
  labels:
    app: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: attach
        image: alpine 
        command: ["sh", "-c", "sleep infinity"]