kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-pvc
  namespace: goerli
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
