#1. change desired pvc claim ref and namespace 
#2. scale down relevant statefulset: "kubectl scale statefulsets geth-teku --replicas=0 -n goerli"
#3. apply this deployment
#4. attach and do stuff: "kubectl exec --stdin --tty busybox-5cc8f6f7f4-r5wxn -n mainnet -- /bin/sh"
#5. delete deployment and scale replicas to 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-attach
  namespace: mainnet
  labels:
    app: pvc-attach
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvc-attach
  template:
    metadata:
      labels:
        app: pvc-attach
    spec:
      containers:
      - name: attach
        image: alpine
        command: ["sh", "-c", "sleep infinity"]   
        volumeMounts:
        - name: pvc-data-1
          mountPath: /data1
        - name: pvc-data-2
          mountPath: /data2
      volumes:
        - name: pvc-data-1
          persistentVolumeClaim:
            claimName: eth-pvc-geth-prysm-0
        - name: pvc-data-2
          persistentVolumeClaim:
            claimName: eth-pvc-geth-lighthouse-0
