# attach and do stuff: "kubectl exec -it cleanup -n mainnet -- /bin/sh"
apiVersion: v1
kind: Pod
metadata:
  name: cleanup
spec:
  containers:
  - image: austonst/cron-backup-postgres:latest
    command:
      - "sleep"
      - "86400"
    imagePullPolicy: IfNotPresent
    name: cleanup
    volumeMounts:
    - mountPath: /backup
      name: backup
    env:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: username
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: password
    - name: POSTGRES_URI
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: host
    - name: POSTGRES_PORT
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: port

  restartPolicy: Always
  volumes:
  - name: backup
    persistentVolumeClaim:
      claimName: backup-pvc
