#1. kubectl scale --replicas=0 sts [geth-teku | geth prysm] -n mainnet
#2. use the correct pvc and builder image
#3. kubectl apply -f <this_script>
#4. attach and do stuff: "kubectl exec --stdin --tty geth-teku- -n mainnet -- /bin/sh"
#6. apk add tmux/screen and geth prune-state --data_dir = /data or do it from this script directly
#5. kubectl scale --replicas=1 sts geth-teku -n mainnet
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth-prune
  namespace: mainnet
  labels:
    app: geth-prune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geth-prune
  template:
    metadata:
      labels:
        app: geth-prune
    spec:
      containers:
      - name: geth-prune
        image: austonst/builder@sha256:2e77ea3a17045184fd92b9bb9892a67854eec9325a82bce240364e6318fe0ebc
        command: ["geth", "snapshot", "prune-state", "--datadir=/data/geth"]
        volumeMounts:
        - name: eth-data
          mountPath: /data
      volumes:
        - name: eth-data
          persistentVolumeClaim:
            claimName: eth-pvc-geth-lighthouse-2
