apiVersion: batch/v1
kind: Job
metadata:
  name: get-builder-status
  namespace: goerli
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        app: update-builder
    spec:
      restartPolicy: Never
      containers:
      - name: update-builder
        image: austonst/update-builder:latest
        command: ["python", "/app/updateBuilder.py"]
        args: ["--url", "http://relay-api-internal:9062/internal/v1/builder", "--function", "builderStatus", "--pubkey", "0xaa1488eae4b06a1fff840a2b6db167afc520758dc2c8af0dfb57037954df3431b747e2f900fe8805f05d635e9a29717b", "--method", "get"]