auth:
  enabled: true
  existingSecret: redis
  existingSecretPasswordKey: password

tls:
  enabled: false

master:
  persistence:
    enabled: true
    storageClass: csi-cinder-high-speed
    accessMode: ReadWriteOnce
    size: "3Gi"
  resources:
    requests:
      memory: "2Gi"
      cpu: "1500m"
    limits:
      memory: "2Gi"

replica:
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: csi-cinder-high-speed
    accessMode: ReadWriteOnce
    size: "3Gi"
  resources:
    requests:
      memory: "2Gi"
      cpu: "1500m"
    limits:
      memory: "2Gi"

metrics:
  enabled: true
  resources:
    requests:
      memory: "50Mi"
      cpu: "50m"
    limits:
      memory: "50Mi"
