architecture: high-availability
replicaCount: 2

extraEnvVars:
  - name: MEMCACHED_CACHE_SIZE
    value: "3000"
  - name: MEMCACHED_MAX_ITEM_SIZE
    value: "8388608"

resources:
  requests:
    memory: 4Gi
    cpu: "1000m"
  limits:
    memory: 4Gi

persistence:
  enabled: true
  storageClass: csi-cinder-high-speed
  accessMode: ReadWriteOnce
  size: 8Gi
