architecture: high-availability
replicaCount: 2

extraEnvVars:
  - name: MEMCACHED_CACHE_SIZE
    value: "512"
  - name: MEMCACHED_MAX_ITEM_SIZE
    value: "8388608"

resources:
  requests:
    memory: 1Gi
    cpu: "250m"
  limits:
    memory: 1Gi

persistence:
  enabled: true
  storageClass: csi-cinder-high-speed
  accessMode: ReadWriteOnce
  size: 8Gi
