usePassword: true
existingSecret: redis
existingSecretPasswordKey: password

tls:
  enabled: false

persistence:
  enabled: true
  storageClass: csi-cinder-high-speed
  accessMode: ReadWriteOnce
  size: "2500Mi"

redis:
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "2Gi"

metrics:
  enabled: true
